name: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Release to GitHub
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            conventional-changelog-conventionalcommits@6.1.0
          branches: |
            master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
